import { v4 as uuid } from 'uuid';

function textElement(overrides = {}) {
  return {
    id: uuid(),
    type: 'text',
    x: 100,
    y: 100,
    width: 400,
    height: 60,
    rotation: 0,
    zIndex: 1,
    text: 'Click to edit text',
    fontSize: 24,
    fontFamily: 'Inter',
    fontWeight: 'normal',
    fontStyle: 'normal',
    textDecoration: '',
    fill: '#0f172a',
    align: 'left',
    verticalAlign: 'top',
    ...overrides,
  };
}

function shapeElement(overrides = {}) {
  return {
    id: uuid(),
    type: 'rect',
    x: 100,
    y: 100,
    width: 200,
    height: 120,
    rotation: 0,
    zIndex: 0,
    fill: '#dbeafe',
    stroke: '#2563eb',
    strokeWidth: 2,
    cornerRadius: 8,
    ...overrides,
  };
}

export const SLIDE_LAYOUTS = {
  blank: {
    id: 'blank',
    name: 'Blank',
    elements: () => [],
  },
  title: {
    id: 'title',
    name: 'Title Slide',
    elements: (theme) => [
      textElement({
        x: 120,
        y: 380,
        width: 1680,
        height: 120,
        text: 'Presentation Title',
        fontSize: 56,
        fontWeight: 'bold',
        fill: theme.text,
        align: 'center',
        zIndex: 1,
      }),
      textElement({
        x: 120,
        y: 520,
        width: 1680,
        height: 60,
        text: 'Subtitle goes here',
        fontSize: 28,
        fill: theme.secondary,
        align: 'center',
        zIndex: 2,
      }),
    ],
  },
  'title-content': {
    id: 'title-content',
    name: 'Title + Content',
    elements: (theme) => [
      textElement({
        x: 80,
        y: 60,
        width: 1760,
        height: 80,
        text: 'Slide Title',
        fontSize: 40,
        fontWeight: 'bold',
        fill: theme.text,
        zIndex: 1,
      }),
      textElement({
        x: 80,
        y: 180,
        width: 1760,
        height: 800,
        text: '• First point\n• Second point\n• Third point',
        fontSize: 24,
        fill: theme.text,
        zIndex: 2,
      }),
    ],
  },
  comparison: {
    id: 'comparison',
    name: 'Comparison',
    elements: (theme) => [
      textElement({
        x: 80,
        y: 40,
        width: 1760,
        height: 70,
        text: 'Compare Options',
        fontSize: 36,
        fontWeight: 'bold',
        fill: theme.text,
        align: 'center',
        zIndex: 3,
      }),
      shapeElement({
        x: 80,
        y: 140,
        width: 840,
        height: 860,
        fill: theme.primary + '15',
        stroke: theme.primary,
        zIndex: 0,
      }),
      shapeElement({
        x: 1000,
        y: 140,
        width: 840,
        height: 860,
        fill: theme.accent + '15',
        stroke: theme.accent,
        zIndex: 0,
      }),
      textElement({
        x: 120,
        y: 180,
        width: 760,
        height: 50,
        text: 'Option A',
        fontSize: 28,
        fontWeight: 'bold',
        fill: theme.primary,
        zIndex: 1,
      }),
      textElement({
        x: 1040,
        y: 180,
        width: 760,
        height: 50,
        text: 'Option B',
        fontSize: 28,
        fontWeight: 'bold',
        fill: theme.accent,
        zIndex: 2,
      }),
    ],
  },
  'two-column': {
    id: 'two-column',
    name: 'Two Column',
    elements: (theme) => [
      textElement({
        x: 80,
        y: 40,
        width: 1760,
        height: 70,
        text: 'Two Column Layout',
        fontSize: 36,
        fontWeight: 'bold',
        fill: theme.text,
        zIndex: 1,
      }),
      textElement({
        x: 80,
        y: 140,
        width: 840,
        height: 860,
        text: 'Left column content',
        fontSize: 22,
        fill: theme.text,
        zIndex: 2,
      }),
      textElement({
        x: 1000,
        y: 140,
        width: 840,
        height: 860,
        text: 'Right column content',
        fontSize: 22,
        fill: theme.text,
        zIndex: 3,
      }),
    ],
  },
};
