export const THEMES = {
  default: {
    id: 'default',
    name: 'Default',
    primary: '#2563eb',
    secondary: '#64748b',
    accent: '#0ea5e9',
    background: '#ffffff',
    text: '#0f172a',
    headingFont: 'Inter',
    bodyFont: 'Inter',
  },
  midnight: {
    id: 'midnight',
    name: 'Midnight',
    primary: '#818cf8',
    secondary: '#94a3b8',
    accent: '#c084fc',
    background: '#0f172a',
    text: '#f8fafc',
    headingFont: 'Inter',
    bodyFont: 'Inter',
  },
  forest: {
    id: 'forest',
    name: 'Forest',
    primary: '#059669',
    secondary: '#6b7280',
    accent: '#34d399',
    background: '#f0fdf4',
    text: '#14532d',
    headingFont: 'Georgia',
    bodyFont: 'Inter',
  },
  sunset: {
    id: 'sunset',
    name: 'Sunset',
    primary: '#ea580c',
    secondary: '#78716c',
    accent: '#fbbf24',
    background: '#fffbeb',
    text: '#431407',
    headingFont: 'Georgia',
    bodyFont: 'Inter',
  },
  corporate: {
    id: 'corporate',
    name: 'Corporate',
    primary: '#1e40af',
    secondary: '#475569',
    accent: '#0284c7',
    background: '#f8fafc',
    text: '#1e293b',
    headingFont: 'Inter',
    bodyFont: 'Inter',
  },
};

export const FONT_LIBRARY = [
  'Inter',
  'Georgia',
  'Times New Roman',
  'Arial',
  'Helvetica',
  'Verdana',
  'Courier New',
  'Trebuchet MS',
  'Palatino',
  'Garamond',
];
